// <auto-generated />
using GeografisApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeografisApi.Migrations
{
    [DbContext(typeof(GeografisContext))]
    [Migration("20231122015829_AddUmkmToDatabase")]
    partial class AddUmkmToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("GeografisApi.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("kategori")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kategoris");
                });

            modelBuilder.Entity("GeografisApi.Models.Umkm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("alamat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("deskripsi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("gambar1")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("gambar2")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("gambar3")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("kategori")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("lattitude")
                        .HasColumnType("double");

                    b.Property<double>("longitude")
                        .HasColumnType("double");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Umkms");
                });
#pragma warning restore 612, 618
        }
    }
}
